import com.encima.dwc.DarwinCore

import com.encima.dwc.Occurrence

import com.encima.dwc.Location

import com.encima.dwc.Species

import com.encima.dwc.Identification

import com.encima.utils.DBTools

import com.encima.utils.TimeTools

import java.util.Collection;

import java.util.Date;

rule "Time Frame" 
	when 
		archive:DarwinCore(archive.getOcc().getEventDate() == "27-MAR-2012")
	then
		System.out.println("Date is March");
	end 

rule "Otter River" 
	when
		$dwc:DarwinCore()
		DarwinCore(DBTools.getLocationDescription($dwc.getOcc().getLocationID()) contains "River")
		eval(TimeTools.checkTimePeriod($dwc.getOcc().getEventTime()) == "Afternoon")
	then
		System.out.println("Otter");
		int id = $dwc.getOcc().getEventID();
		Date d = new Date();
		Identification ident = new Identification(id, 1, d, 1);
		$dwc.setId(ident);
		System.out.println($dwc.getId());
	end
	
rule "Plantation Night"
	when
		$dwc:DarwinCore()
		DarwinCore(DBTools.getLocationDescription($dwc.getOcc().getLocationID()) contains "Plantation")
		eval(TimeTools.checkTimePeriod($dwc.getOcc().getEventTime()) == "Night")
	then
		System.out.println("Sun Bear or Civet");
	end

rule "Clouded Leopard Ridgeline"
	when
		$dwc:DarwinCore()
		DarwinCore(DBTools.getLocationDescription($dwc.getOcc().getLocationID()) contains "Ridge Line")
		eval(TimeTools.checkTimePeriod($dwc.getOcc().getEventTime()) == "Night")
	then
		System.out.println("Clouded Leopard - Most likely male");
	end

rule "Location Description"
	when
		$dwc:DarwinCore()
		eval($dwc.getOcc().getLocationID()==1)
	then
		System.out.println("Occurence in site 1, animals here are: Clouded Leopard, Malay Civets and Small Mammals");
	end
