#!/bin/bash
pdflatex thesis.tex
bibtex thesis
bibtex thesis
pdflatex thesis.tex
pdflatex thesis.tex
now=`date +"%m_%d_%Y"`
mv thesis.pdf output/thesis_chris_$now.pdf
open output/thesis_chris_$now.pdf
